config/routes.rb
Rails.application.routes.draw do
  resources :urls, only: [:create, :show], controller: 'short_urls' do
    resource :stats, only: [:show]
  end

  root 'short_urls#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/short_url.rb
require 'short_url_coder'

class ShortUrl < ApplicationRecord
  validates :url, presence: true

  def self.find_by_short_url(short_url)
    id = ShortUrlCoder.decode(short_url)
    find(id)
  end

  def short_url
    return unless id

    ShortUrlCoder.encode(id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController
  def index
    render :new, locals: { short_url: ShortUrl.new }
  end

  def show
    short_url = ShortUrl.find_by_short_url(params[:id])
    short_url.increment(:counter)
    short_url.update!(visitor_ip: request.remote_ip, visited_at: Time.current)
    redirect_to short_url.url
  end

  def create
    short_url = ShortUrl.new(short_url_params)

    if short_url.save
      render :show, status: :created, locals: { short_url: short_url }
    else
      render json: { errors: short_url.errors, messages: short_url.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def short_url_params
    params.require(:short_url).permit(:url)
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def show
    short_url = ShortUrl.find_by_short_url(params[:url_id])
    render locals: { short_url: short_url }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShorterer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/short_urls/_form.html.erb
<%= form_with(model: short_url, url: urls_path, local: false, id: 'new-short-url') do |form| %>
    <div id="error_explanation" style="display: none">
      <h2><%= pluralize(short_url.errors.count, "error") %> prohibited this stat from being saved:</h2>

      <ul>
        <% short_url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit 'Сократить' %>
  </div>
<% end %>

<script>
    window.addEventListener("load", () => {
        const element = document.querySelector("#new-short-url");
        element.addEventListener("ajax:success", (event) => {
            const [_data, _status, xhr] = event.detail;
            window.location.href = `/urls/${JSON.parse(xhr.response).short_url}/stats`;
        });
        element.addEventListener("ajax:error", (event) => {
            const [_data, _status, xhr] = event.detail;
            const err_element = document.getElementById('error_explanation');
            var err_list = '<ul>';
            JSON.parse(xhr.response).messages.forEach(err => {
                err_list += `<li>${err}</li>`;
            });
            err_list += '</ul>'
            err_element.innerHTML = err_list;
            err_element.style.display = '';
        });
    });
</script>

app/views/short_urls/new.html.erb
<%= render 'form', short_url: short_url %>

app/views/stats/show.html.erb
<p>
  <strong>Url:</strong>
  <%= short_url.url %>
</p>

<p>
  <strong>Short url:</strong>
  <%= url_url(id: short_url.short_url) %>
</p>

<p>
  <strong>Counter:</strong>
  <%= short_url.counter %>
</p>

<p>
  <strong>Visitor ip:</strong>
  <%= short_url.visitor_ip %>
</p>

<p>
  <strong>Visited at:</strong>
  <%= short_url.visited_at %>
</p>